# Generated by Django 3.2.16 on 2023-02-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_amount',
            field=models.FloatField(default=0, verbose_name='Delivery amount'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='ecommerce.Product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products_amount',
            field=models.FloatField(default=0, verbose_name='Products amount'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Total amount'),
        ),
    ]
