# Generated by Django 3.2.16 on 2023-02-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.CreateModel(
            name='ProductAtCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecommerce.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products_at_cart',
            field=models.ManyToManyField(blank=True, related_name='products', to='ecommerce.ProductAtCart', verbose_name='Products'),
        ),
    ]
