# Generated by Django 3.2.16 on 2023-02-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20230212_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='productatcart',
            name='product_name',
            field=models.CharField(default='', max_length=124, verbose_name='Name'),
        ),
    ]
